language: ruby
rvm: 2.3.1
cache: bundler
script:
- bundle exec rake
- bundle exec rubocop
after_success:
- bash bin/deploy $ARTIFACTORY_PASSWORD
env:
  global:
    secure: AUsV9GePQzTpbOTSdTe77uS/u+pnN7gTYGX9MuJDYb5r84UEXZ65cjL/IJZWFQIksdqjuQW5DnK6hLU11MdEqsy3sP116tLTTr0dSQrJh8DPntestdwz+tAQOvUFTJuEgS5pqgLO4eFtxBnwJaP2W51anhaqCez6lNL4KMpm+2TlFO3fCihEpDIwvNb1cnsP7TDaVpkEsZKjTajTnxlgHKPfNuC6gb5IA/yi+bEMh+Q3LIUX6DORYnFVG1UQert4tYxHM9y08u6c8V5a3wFbVy7uIcu2RDmvPUZejaaEsQF5VXX9JUAMmMQgQCCFBHqFgBlGV4BNggZNndGQd4hj1nobiTggBzRAPd0moyMrLbUo00GkyLuw+65TTGpTWwTFCZoetbqQl8tblWrRifmPE9876nCydy4te12fNFwe27fnmjTlPGM+Ow7NQyrYDDubXiTDJXpIKx+HE+RRIBkxh5lORvlOIegEDE7jj2ZnvgzrXCPtM3b1H/LWJrE0BcHYJd4V25NhnQPVzMQZZnM3K/WEkwTBR35sI21kTYYZNCYQBsAS7XtsQ3aDcqQTSTQKIWXnavRw+IcrBJnfOa7zAr7kJiNK6H/Li8mGMTjfsdtkvUhlRaS5LjX4Yl7Gz243IAsxVo/hKams0/vcMmwmbpJHerr6gIaOPUrqZwMt0Hs=
